
const countrySelect = document.getElementById('country');
const stateSelect = document.getElementById('state');
const citySelect = document.getElementById('city');


    const statesByCountry = {
        "US": [
          { code: "AL", name: "Alabama" },
          { code: "AK", name: "Alaska" },
          { code: "AZ", name: "Arizona" },
          { code: "AR", name: "Arkansas" },
          { code: "CA", name: "California" },
          { code: "CO", name: "Colorado" },
          { code: "CT", name: "Connecticut" },
          { code: "DE", name: "Delaware" },
          { code: "FL", name: "Florida" },
          { code: "GA", name: "Georgia" },
          { code: "HI", name: "Hawaii" },
          { code: "ID", name: "Idaho" },
          { code: "IL", name: "Illinois" },
          { code: "IN", name: "Indiana" },
          { code: "IA", name: "Iowa" },
          { code: "KS", name: "Kansas" },
          { code: "KY", name: "Kentucky" },
          { code: "LA", name: "Louisiana" },
          { code: "ME", name: "Maine" },
          { code: "MD", name: "Maryland" },
          { code: "MA", name: "Massachusetts" },
          { code: "MI", name: "Michigan" },
          { code: "MN", name: "Minnesota" },
          { code: "MS", name: "Mississippi" },
          { code: "MO", name: "Missouri" },
          { code: "MT", name: "Montana" },
          { code: "NE", name: "Nebraska" },
          { code: "NV", name: "Nevada" },
          { code: "NH", name: "New Hampshire" },
          { code: "NJ", name: "New Jersey" },
          { code: "NM", name: "New Mexico" },
          { code: "NY", name: "New York" },
          { code: "NC", name: "North Carolina" },
          { code: "ND", name: "North Dakota" },
          { code: "OH", name: "Ohio" },
          { code: "OK", name: "Oklahoma" },
          { code: "OR", name: "Oregon" },
          { code: "PA", name: "Pennsylvania" },
          { code: "RI", name: "Rhode Island" },
          { code: "SC", name: "South Carolina" },
          { code: "SD", name: "South Dakota" },
          { code: "TN", name: "Tennessee" },
          { code: "TX", name: "Texas" },
          { code: "UT", name: "Utah" },
          { code: "VT", name: "Vermont" },
          { code: "VA", name: "Virginia" },
          { code: "WA", name: "Washington" },
          { code: "WV", name: "West Virginia" },
          { code: "WI", name: "Wisconsin" },
          { code: "WY", name: "Wyoming" },
        ],
        "UK": [
          { code: "EN", name: "England" },
          { code: "SC", name: "Scotland" },
          { code: "NI", name: "Northern Ireland" },
          { code: "WS", name: "Wales" },
        ],
        "MM": [
            { code: "ကချင်ပြည်နယ်", name: "KCS" },
            { code: "ကယားပြည်နယ်", name: "KRNS" },
            { code: "ကရင်ပြည်နယ်", name: "KYS" },
            { code: "ချင်းပြည်နယ်", name: "CS" },
            { code: "စစ်ကိုင်းတိုင်းဒေသကြီး", name: "SGR" },
            { code: "တနင်္သာရီတိုင်းဒေသကြီး", name: "TNTRR" },
            { code: "ပဲခူးတိုင်းဒေသကြီး", name: "BGR" },
            { code: "မကွေးတိုင်းဒေသကြီး", name: "MGR" },
            { code: "မန္တလေးတိုင်းဒေသကြီး", name: "MDYR" },
            { code: "မွန်ပြည်နယ်", name: "MS" },
            { code: "ရခိုင်ပြည်နယ်", name: "RKS" },
            { code: "ရန်ကုန်တိုင်းဒေသကြီး", name: "YGR" },
            { code: "ရှမ်းပြည်နယ်", name: "SS" },
            { code: "ဧရာဝတီတိုင်းဒေသကြီး", name: "AYWR" }

        ]
       
      };

const citiesByCountry = {
       
    "US": {
            "AL": [
                "Alexander City",
                "Andalusia",
                "Anniston",
                "Athens",
                "Atmore",
                "Auburn",
                "Bessemer",
                "Birmingham",
                "Chickasaw",
                "Clanton",
                "Cullman",
                "Decatur",
                "Demopolis",
                "Dothan",
                "Enterprise",
                "Eufaula",
                "Florence",
                "Fort Payne",
                "Gadsden",
                "Greenville",
                "Guntersville",
                "Huntsville",
                "Jasper",
                "Marion",
                "Mobile",
                "Montgomery",
                "Opelika",
                "Ozark",
                "Phenix City",
                "Prichard",
                "Scottsboro",
                "Selma",
                "Sheffield",
                "Sylacauga",
                "Talladega",
                "Troy",
                "Tuscaloosa",
                "Tuscumbia",
                "Tuskegee"
            ],
            "AK": [
                "Anchorage",
                "Cordova",
                "Fairbanks",
                "Haines",
                "Homer",
                "Juneau",
                "Ketchikan",
                "Kodiak",
                "Kotzebue",
                "Nome",
                "Palmer",
                "Seward",
                "Sitka",
                "Skagway",
                "Valdez"
            ],
            "AZ": [
                "Ajo",
                "Avondale",
                "Bisbee",
                "Casa Grande",
                "Chandler",
                "Clifton",
                "Douglas",
                "Flagstaff",
                "Florence",
                "Gila Bend",
                "Glendale",
                "Globe",
                "Kingman",
                "Lake Havasu City",
                "Mesa",
                "Nogales",
                "Oraibi",
                "Phoenix",
                "Prescott",
                "Scottsdale",
                "Sierra Vista",
                "Tempe",
                "Tombstone",
                "Tucson",
                "Walpi",
                "Window Rock",
                "Winslow",
                "Yuma"
            ],
            "AR": [
                "Arkadelphia",
                "Arkansas Post",
                "Batesville",
                "Benton",
                "Blytheville",
                "Camden",
                "Conway",
                "Crossett",
                "El Dorado",
                "Fayetteville",
                "Forrest City",
                "Fort Smith",
                "Harrison",
                "Helena",
                "Hope",
                "Hot Springs",
                "Jacksonville",
                "Jonesboro",
                "Little Rock",
                "Magnolia",
                "Morrilton",
                "Newport",
                "North Little Rock",
                "Osceola",
                "Pine Bluff",
                "Rogers",
                "Searcy",
                "Stuttgart",
                "Van Buren",
                "West Memphis"
            ],
            "CA": [
                "Alameda",
                "Alhambra",
                "Anaheim",
                "Antioch",
                "Arcadia",
                "Bakersfield",
                "Barstow",
                "Belmont",
                "Berkeley",
                "Beverly Hills",
                "Brea",
                "Buena Park",
                "Burbank",
                "Calexico",
                "Calistoga",
                "Carlsbad",
                "Carmel",
                "Chico",
                "Chula Vista",
                "Claremont",
                "Compton",
                "Concord",
                "Corona",
                "Coronado",
                "Costa Mesa",
                "Culver City",
                "Daly City",
                "Davis",
                "Downey",
                "El Centro",
                "El Cerrito",
                "El Monte",
                "Escondido",
                "Eureka",
                "Fairfield",
                "Fontana",
                "Fremont",
                "Fresno",
                "Fullerton",
                "Garden Grove",
                "Glendale",
                "Hayward",
                "Hollywood",
                "Huntington Beach",
                "Indio",
                "Inglewood",
                "Irvine",
                "La Habra",
                "Laguna Beach",
                "Lancaster",
                "Livermore",
                "Lodi",
                "Lompoc",
                "Long Beach",
                "Los Angeles",
                "Malibu",
                "Martinez",
                "Marysville",
                "Menlo Park",
                "Merced",
                "Modesto",
                "Monterey",
                "Mountain View",
                "Napa",
                "Needles",
                "Newport Beach",
                "Norwalk",
                "Novato",
                "Oakland",
                "Oceanside",
                "Ojai",
                "Ontario",
                "Orange",
                "Oroville",
                "Oxnard",
                "Pacific Grove",
                "Palm Springs",
                "Palmdale",
                "Palo Alto",
                "Pasadena",
                "Petaluma",
                "Pomona",
                "Port Hueneme",
                "Rancho Cucamonga",
                "Red Bluff",
                "Redding",
                "Redlands",
                "Redondo Beach",
                "Redwood City",
                "Richmond",
                "Riverside",
                "Roseville",
                "Sacramento",
                "Salinas",
                "San Bernardino",
                "San Clemente",
                "San Diego",
                "San Fernando",
                "San Francisco",
                "San Gabriel",
                "San Jose",
                "San Juan Capistrano",
                "San Leandro",
                "San Luis Obispo",
                "San Marino",
                "San Mateo",
                "San Pedro",
                "San Rafael",
                "San Simeon",
                "Santa Ana",
                "Santa Barbara",
                "Santa Clara",
                "Santa Clarita",
                "Santa Cruz",
                "Santa Monica",
                "Santa Rosa",
                "Sausalito",
                "Simi Valley",
                "Sonoma",
                "South San Francisco",
                "Stockton",
                "Sunnyvale",
                "Susanville",
                "Thousand Oaks",
                "Torrance",
                "Turlock",
                "Ukiah",
                "Vallejo",
                "Ventura",
                "Victorville",
                "Visalia",
                "Walnut Creek",
                "Watts",
                "West Covina",
                "Whittier",
                "Woodland",
                "Yorba Linda",
                "Yuba City"
            ],
            "CO": [
                "Alamosa",
                "Aspen",
                "Aurora",
                "Boulder",
                "Breckenridge",
                "Brighton",
                "Canon City",
                "Central City",
                "Climax",
                "Colorado Springs",
                "Cortez",
                "Cripple Creek",
                "Denver",
                "Durango",
                "Englewood",
                "Estes Park",
                "Fort Collins",
                "Fort Morgan",
                "Georgetown",
                "Glenwood Springs",
                "Golden",
                "Grand Junction",
                "Greeley",
                "Gunnison",
                "La Junta",
                "Leadville",
                "Littleton",
                "Longmont",
                "Loveland",
                "Montrose",
                "Ouray",
                "Pagosa Springs",
                "Pueblo",
                "Silverton",
                "Steamboat Springs",
                "Sterling",
                "Telluride",
                "Trinidad",
                "Vail",
                "Walsenburg",
                "Westminster"
            ],
            "CT": [
                "Ansonia",
                "Berlin",
                "Bloomfield",
                "Branford",
                "Bridgeport",
                "Bristol",
                "Coventry",
                "Danbury",
                "Darien",
                "Derby",
                "East Hartford",
                "East Haven",
                "Enfield",
                "Fairfield",
                "Farmington",
                "Greenwich",
                "Groton",
                "Guilford",
                "Hamden",
                "Hartford",
                "Lebanon",
                "Litchfield",
                "Manchester",
                "Mansfield",
                "Meriden",
                "Middletown",
                "Milford",
                "Mystic",
                "Naugatuck",
                "New Britain",
                "New Haven",
                "New London",
                "North Haven",
                "Norwalk",
                "Norwich",
                "Old Saybrook",
                "Orange",
                "Seymour",
                "Shelton",
                "Simsbury",
                "Southington",
                "Stamford",
                "Stonington",
                "Stratford",
                "Torrington",
                "Wallingford",
                "Waterbury",
                "Waterford",
                "Watertown",
                "West Hartford",
                "West Haven",
                "Westport",
                "Wethersfield",
                "Willimantic",
                "Windham",
                "Windsor",
                "Windsor Locks",
                "Winsted"
            ],
            "DE": [
                "Dover",
                "Lewes",
                "Milford",
                "New Castle",
                "Newark",
                "Smyrna",
                "Wilmington"
            ],
            "FL": [
                "Apalachicola",
                "Bartow",
                "Belle Glade",
                "Boca Raton",
                "Bradenton",
                "Cape Coral",
                "Clearwater",
                "Cocoa Beach",
                "Cocoa-Rockledge",
                "Coral Gables",
                "Daytona Beach",
                "De Land",
                "Deerfield Beach",
                "Delray Beach",
                "Fernandina Beach",
                "Fort Lauderdale",
                "Fort Myers",
                "Fort Pierce",
                "Fort Walton Beach",
                "Gainesville",
                "Hallandale Beach",
                "Hialeah",
                "Hollywood",
                "Homestead",
                "Jacksonville",
                "Key West",
                "Lake City",
                "Lake Wales",
                "Lakeland",
                "Largo",
                "Melbourne",
                "Miami",
                "Miami Beach",
                "Naples",
                "New Smyrna Beach",
                "Ocala",
                "Orlando",
                "Ormond Beach",
                "Palatka",
                "Palm Bay",
                "Palm Beach",
                "Panama City",
                "Pensacola",
                "Pompano Beach",
                "Saint Augustine",
                "Saint Petersburg",
                "Sanford",
                "Sarasota",
                "Sebring",
                "Tallahassee",
                "Tampa",
                "Tarpon Springs",
                "Titusville",
                "Venice",
                "West Palm Beach",
                "White Springs",
                "Winter Haven",
                "Winter Park"
            ],
            "GA": [
                "Albany",
                "Americus",
                "Andersonville",
                "Athens",
                "Atlanta",
                "Augusta",
                "Bainbridge",
                "Blairsville",
                "Brunswick",
                "Calhoun",
                "Carrollton",
                "Columbus",
                "Dahlonega",
                "Dalton",
                "Darien",
                "Decatur",
                "Douglas",
                "East Point",
                "Fitzgerald",
                "Fort Valley",
                "Gainesville",
                "La Grange",
                "Macon",
                "Marietta",
                "Milledgeville",
                "Plains",
                "Rome",
                "Savannah",
                "Toccoa",
                "Valdosta",
                "Warm Springs",
                "Warner Robins",
                "Washington",
                "Waycross"
            ],
            "HI": [
                "Hanalei",
                "Hilo",
                "Honaunau",
                "Honolulu",
                "Kahului",
                "Kaneohe",
                "Kapaa",
                "Kawaihae",
                "Lahaina",
                "Laie",
                "Wahiawa",
                "Wailuku",
                "Waimea"
            ],
            "ID": [
                "Blackfoot",
                "Boise",
                "Bonners Ferry",
                "Caldwell",
                "Coeur d’Alene",
                "Idaho City",
                "Idaho Falls",
                "Kellogg",
                "Lewiston",
                "Moscow",
                "Nampa",
                "Pocatello",
                "Priest River",
                "Rexburg",
                "Sun Valley",
                "Twin Falls"
            ],
            "IL": [
                "Alton",
                "Arlington Heights",
                "Arthur",
                "Aurora",
                "Belleville",
                "Belvidere",
                "Bloomington",
                "Brookfield",
                "Cahokia",
                "Cairo",
                "Calumet City",
                "Canton",
                "Carbondale",
                "Carlinville",
                "Carthage",
                "Centralia",
                "Champaign",
                "Charleston",
                "Chester",
                "Chicago",
                "Chicago Heights",
                "Cicero",
                "Collinsville",
                "Danville",
                "Decatur",
                "DeKalb",
                "Des Plaines",
                "Dixon",
                "East Moline",
                "East Saint Louis",
                "Effingham",
                "Elgin",
                "Elmhurst",
                "Evanston",
                "Freeport",
                "Galena",
                "Galesburg",
                "Glen Ellyn",
                "Glenview",
                "Granite City",
                "Harrisburg",
                "Herrin",
                "Highland Park",
                "Jacksonville",
                "Joliet",
                "Kankakee",
                "Kaskaskia",
                "Kewanee",
                "La Salle",
                "Lake Forest",
                "Libertyville",
                "Lincoln",
                "Lisle",
                "Lombard",
                "Macomb",
                "Mattoon",
                "Moline",
                "Monmouth",
                "Mount Vernon",
                "Mundelein",
                "Naperville",
                "Nauvoo",
                "Normal",
                "North Chicago",
                "Oak Park",
                "Oregon",
                "Ottawa",
                "Palatine",
                "Park Forest",
                "Park Ridge",
                "Pekin",
                "Peoria",
                "Petersburg",
                "Pontiac",
                "Quincy",
                "Rantoul",
                "River Forest",
                "Rock Island",
                "Rockford",
                "Salem",
                "Shawneetown",
                "Skokie",
                "South Holland",
                "Springfield",
                "Streator",
                "Summit",
                "Urbana",
                "Vandalia",
                "Virden",
                "Waukegan",
                "Wheaton",
                "Wilmette",
                "Winnetka",
                "Wood River",
                "Zion"
            ],
            "IN": [
                "Anderson",
                "Bedford",
                "Bloomington",
                "Columbus",
                "Connersville",
                "Corydon",
                "Crawfordsville",
                "East Chicago",
                "Elkhart",
                "Elwood",
                "Evansville",
                "Fort Wayne",
                "French Lick",
                "Gary",
                "Geneva",
                "Goshen",
                "Greenfield",
                "Hammond",
                "Hobart",
                "Huntington",
                "Indianapolis",
                "Jeffersonville",
                "Kokomo",
                "Lafayette",
                "Madison",
                "Marion",
                "Michigan City",
                "Mishawaka",
                "Muncie",
                "Nappanee",
                "Nashville",
                "New Albany",
                "New Castle",
                "New Harmony",
                "Peru",
                "Plymouth",
                "Richmond",
                "Santa Claus",
                "Shelbyville",
                "South Bend",
                "Terre Haute",
                "Valparaiso",
                "Vincennes",
                "Wabash",
                "West Lafayette"
            ],
            "IA": [
                "Amana Colonies",
                "Ames",
                "Boone",
                "Burlington",
                "Cedar Falls",
                "Cedar Rapids",
                "Charles City",
                "Cherokee",
                "Clinton",
                "Council Bluffs",
                "Davenport",
                "Des Moines",
                "Dubuque",
                "Estherville",
                "Fairfield",
                "Fort Dodge",
                "Grinnell",
                "Indianola",
                "Iowa City",
                "Keokuk",
                "Mason City",
                "Mount Pleasant",
                "Muscatine",
                "Newton",
                "Oskaloosa",
                "Ottumwa",
                "Sioux City",
                "Waterloo",
                "Webster City",
                "West Des Moines"
            ],
            "KS": [
                "Abilene",
                "Arkansas City",
                "Atchison",
                "Chanute",
                "Coffeyville",
                "Council Grove",
                "Dodge City",
                "Emporia",
                "Fort Scott",
                "Garden City",
                "Great Bend",
                "Hays",
                "Hutchinson",
                "Independence",
                "Junction City",
                "Kansas City",
                "Lawrence",
                "Leavenworth",
                "Liberal",
                "Manhattan",
                "McPherson",
                "Medicine Lodge",
                "Newton",
                "Olathe",
                "Osawatomie",
                "Ottawa",
                "Overland Park",
                "Pittsburg",
                "Salina",
                "Shawnee",
                "Smith Center",
                "Topeka",
                "Wichita"
            ],
            "KY": [
                "Ashland",
                "Barbourville",
                "Bardstown",
                "Berea",
                "Boonesborough",
                "Bowling Green",
                "Campbellsville",
                "Covington",
                "Danville",
                "Elizabethtown",
                "Frankfort",
                "Harlan",
                "Harrodsburg",
                "Hazard",
                "Henderson",
                "Hodgenville",
                "Hopkinsville",
                "Lexington",
                "Louisville",
                "Mayfield",
                "Maysville",
                "Middlesboro",
                "Newport",
                "Owensboro",
                "Paducah",
                "Paris",
                "Richmond"
            ],
            "LA": [
                "Abbeville",
                "Alexandria",
                "Bastrop",
                "Baton Rouge",
                "Bogalusa",
                "Bossier City",
                "Gretna",
                "Houma",
                "Lafayette",
                "Lake Charles",
                "Monroe",
                "Morgan City",
                "Natchitoches",
                "New Iberia",
                "New Orleans",
                "Opelousas",
                "Ruston",
                "Saint Martinville",
                "Shreveport",
                "Thibodaux"
            ],
            "ME": [
                "Auburn",
                "Augusta",
                "Bangor",
                "Bar Harbor",
                "Bath",
                "Belfast",
                "Biddeford",
                "Boothbay Harbor",
                "Brunswick",
                "Calais",
                "Caribou",
                "Castine",
                "Eastport",
                "Ellsworth",
                "Farmington",
                "Fort Kent",
                "Gardiner",
                "Houlton",
                "Kennebunkport",
                "Kittery",
                "Lewiston",
                "Lubec",
                "Machias",
                "Orono",
                "Portland",
                "Presque Isle",
                "Rockland",
                "Rumford",
                "Saco",
                "Scarborough",
                "Waterville",
                "York"
            ],
            "MD": [
                "Aberdeen",
                "Annapolis",
                "Baltimore",
                "Bethesda-Chevy Chase",
                "Bowie",
                "Cambridge",
                "Catonsville",
                "College Park",
                "Columbia",
                "Cumberland",
                "Easton",
                "Elkton",
                "Emmitsburg",
                "Frederick",
                "Greenbelt",
                "Hagerstown",
                "Hyattsville",
                "Laurel",
                "Oakland",
                "Ocean City",
                "Rockville",
                "Saint Marys City",
                "Salisbury",
                "Silver Spring",
                "Takoma Park",
                "Towson",
                "Westminster"
            ],
            "MA": [
                "Abington",
                "Adams",
                "Amesbury",
                "Amherst",
                "Andover",
                "Arlington",
                "Athol",
                "Attleboro",
                "Barnstable",
                "Bedford",
                "Beverly",
                "Boston",
                "Bourne",
                "Braintree",
                "Brockton",
                "Brookline",
                "Cambridge",
                "Canton",
                "Charlestown",
                "Chelmsford",
                "Chelsea",
                "Chicopee",
                "Clinton",
                "Cohasset",
                "Concord",
                "Danvers",
                "Dartmouth",
                "Dedham",
                "Dennis",
                "Duxbury",
                "Eastham",
                "Edgartown",
                "Everett",
                "Fairhaven",
                "Fall River",
                "Falmouth",
                "Fitchburg",
                "Framingham",
                "Gloucester",
                "Great Barrington",
                "Greenfield",
                "Groton",
                "Harwich",
                "Haverhill",
                "Hingham",
                "Holyoke",
                "Hyannis",
                "Ipswich",
                "Lawrence",
                "Lenox",
                "Leominster",
                "Lexington",
                "Lowell",
                "Ludlow",
                "Lynn",
                "Malden",
                "Marblehead",
                "Marlborough",
                "Medford",
                "Milton",
                "Nahant",
                "Natick",
                "New Bedford",
                "Newburyport",
                "Newton",
                "North Adams",
                "Northampton",
                "Norton",
                "Norwood",
                "Peabody",
                "Pittsfield",
                "Plymouth",
                "Provincetown",
                "Quincy",
                "Randolph",
                "Revere",
                "Salem",
                "Sandwich",
                "Saugus",
                "Somerville",
                "South Hadley",
                "Springfield",
                "Stockbridge",
                "Stoughton",
                "Sturbridge",
                "Sudbury",
                "Taunton",
                "Tewksbury",
                "Truro",
                "Watertown",
                "Webster",
                "Wellesley",
                "Wellfleet",
                "West Bridgewater",
                "West Springfield",
                "Westfield",
                "Weymouth",
                "Whitman",
                "Williamstown",
                "Woburn",
                "Woods Hole",
                "Worcester"
            ],
            "MI": [
                "Adrian",
                "Alma",
                "Ann Arbor",
                "Battle Creek",
                "Bay City",
                "Benton Harbor",
                "Bloomfield Hills",
                "Cadillac",
                "Charlevoix",
                "Cheboygan",
                "Dearborn",
                "Detroit",
                "East Lansing",
                "Eastpointe",
                "Ecorse",
                "Escanaba",
                "Flint",
                "Grand Haven",
                "Grand Rapids",
                "Grayling",
                "Grosse Pointe",
                "Hancock",
                "Highland Park",
                "Holland",
                "Houghton",
                "Interlochen",
                "Iron Mountain",
                "Ironwood",
                "Ishpeming",
                "Jackson",
                "Kalamazoo",
                "Lansing",
                "Livonia",
                "Ludington",
                "Mackinaw City",
                "Manistee",
                "Marquette",
                "Menominee",
                "Midland",
                "Monroe",
                "Mount Clemens",
                "Mount Pleasant",
                "Muskegon",
                "Niles",
                "Petoskey",
                "Pontiac",
                "Port Huron",
                "Royal Oak",
                "Saginaw",
                "Saint Ignace",
                "Saint Joseph",
                "Sault Sainte Marie",
                "Traverse City",
                "Trenton",
                "Warren",
                "Wyandotte",
                "Ypsilanti"
            ],
            "MN": [
                "Albert Lea",
                "Alexandria",
                "Austin",
                "Bemidji",
                "Bloomington",
                "Brainerd",
                "Crookston",
                "Duluth",
                "Ely",
                "Eveleth",
                "Faribault",
                "Fergus Falls",
                "Hastings",
                "Hibbing",
                "International Falls",
                "Little Falls",
                "Mankato",
                "Minneapolis",
                "Moorhead",
                "New Ulm",
                "Northfield",
                "Owatonna",
                "Pipestone",
                "Red Wing",
                "Rochester",
                "Saint Cloud",
                "Saint Paul",
                "Sauk Centre",
                "South Saint Paul",
                "Stillwater",
                "Virginia",
                "Willmar",
                "Winona"
            ],
            "MS": [
                "Bay Saint Louis",
                "Biloxi",
                "Canton",
                "Clarksdale",
                "Columbia",
                "Columbus",
                "Corinth",
                "Greenville",
                "Greenwood",
                "Grenada",
                "Gulfport",
                "Hattiesburg",
                "Holly Springs",
                "Jackson",
                "Laurel",
                "Meridian",
                "Natchez",
                "Ocean Springs",
                "Oxford",
                "Pascagoula",
                "Pass Christian",
                "Philadelphia",
                "Port Gibson",
                "Starkville",
                "Tupelo",
                "Vicksburg",
                "West Point",
                "Yazoo City"
            ],
            "MO": [
                "Boonville",
                "Branson",
                "Cape Girardeau",
                "Carthage",
                "Chillicothe",
                "Clayton",
                "Columbia",
                "Excelsior Springs",
                "Ferguson",
                "Florissant",
                "Fulton",
                "Hannibal",
                "Independence",
                "Jefferson City",
                "Joplin",
                "Kansas City",
                "Kirksville",
                "Lamar",
                "Lebanon",
                "Lexington",
                "Maryville",
                "Mexico",
                "Monett",
                "Neosho",
                "New Madrid",
                "Rolla",
                "Saint Charles",
                "Saint Joseph",
                "Saint Louis",
                "Sainte Genevieve",
                "Salem",
                "Sedalia",
                "Springfield",
                "Warrensburg",
                "West Plains"
            ],
            "MT": [
                "Anaconda",
                "Billings",
                "Bozeman",
                "Butte",
                "Dillon",
                "Fort Benton",
                "Glendive",
                "Great Falls",
                "Havre",
                "Helena",
                "Kalispell",
                "Lewistown",
                "Livingston",
                "Miles City",
                "Missoula",
                "Virginia City"
            ],
            "NE": [
                "Beatrice",
                "Bellevue",
                "Boys Town",
                "Chadron",
                "Columbus",
                "Fremont",
                "Grand Island",
                "Hastings",
                "Kearney",
                "Lincoln",
                "McCook",
                "Minden",
                "Nebraska City",
                "Norfolk",
                "North Platte",
                "Omaha",
                "Plattsmouth",
                "Red Cloud",
                "Sidney"
            ],
            "NV": [
                "Boulder City",
                "Carson City",
                "Elko",
                "Ely",
                "Fallon",
                "Genoa",
                "Goldfield",
                "Henderson",
                "Las Vegas",
                "North Las Vegas",
                "Reno",
                "Sparks",
                "Virginia City",
                "Winnemucca"
            ],
            "NH": [
                "Berlin",
                "Claremont",
                "Concord",
                "Derry",
                "Dover",
                "Durham",
                "Exeter",
                "Franklin",
                "Hanover",
                "Hillsborough",
                "Keene",
                "Laconia",
                "Lebanon",
                "Manchester",
                "Nashua",
                "Peterborough",
                "Plymouth",
                "Portsmouth",
                "Rochester",
                "Salem"
            ],
            "NJ": [
                "Asbury Park",
                "Atlantic City",
                "Bayonne",
                "Bloomfield",
                "Bordentown",
                "Bound Brook",
                "Bridgeton",
                "Burlington",
                "Caldwell",
                "Camden",
                "Cape May",
                "Clifton",
                "Cranford",
                "East Orange",
                "Edison",
                "Elizabeth",
                "Englewood",
                "Fort Lee",
                "Glassboro",
                "Hackensack",
                "Haddonfield",
                "Hoboken",
                "Irvington",
                "Jersey City",
                "Lakehurst",
                "Lakewood",
                "Long Beach",
                "Long Branch",
                "Madison",
                "Menlo Park",
                "Millburn",
                "Millville",
                "Montclair",
                "Morristown",
                "Mount Holly",
                "New Brunswick",
                "New Milford",
                "Newark",
                "Ocean City",
                "Orange",
                "Parsippany–Troy Hills",
                "Passaic",
                "Paterson",
                "Perth Amboy",
                "Plainfield",
                "Princeton",
                "Ridgewood",
                "Roselle",
                "Rutherford",
                "Salem",
                "Somerville",
                "South Orange Village",
                "Totowa",
                "Trenton",
                "Union",
                "Union City",
                "Vineland",
                "Wayne",
                "Weehawken",
                "West New York",
                "West Orange",
                "Willingboro",
                "Woodbridge",
                "Woodbury"
            ],
            "NM": [
                "Acoma",
                "Alamogordo",
                "Albuquerque",
                "Artesia",
                "Belen",
                "Carlsbad",
                "Clovis",
                "Deming",
                "Farmington",
                "Gallup",
                "Grants",
                "Hobbs",
                "Las Cruces",
                "Las Vegas",
                "Los Alamos",
                "Lovington",
                "Portales",
                "Raton",
                "Roswell",
                "Santa Fe",
                "Shiprock",
                "Silver City",
                "Socorro",
                "Taos",
                "Truth or Consequences",
                "Tucumcari"
            ],
            "NY": [
                "Albany",
                "Amsterdam",
                "Auburn",
                "Babylon",
                "Batavia",
                "Beacon",
                "Bedford",
                "Binghamton",
                "Bronx",
                "Brooklyn",
                "Buffalo",
                "Chautauqua",
                "Cheektowaga",
                "Clinton",
                "Cohoes",
                "Coney Island",
                "Cooperstown",
                "Corning",
                "Cortland",
                "Crown Point",
                "Dunkirk",
                "East Aurora",
                "East Hampton",
                "Eastchester",
                "Elmira",
                "Flushing",
                "Forest Hills",
                "Fredonia",
                "Garden City",
                "Geneva",
                "Glens Falls",
                "Gloversville",
                "Great Neck",
                "Hammondsport",
                "Harlem",
                "Hempstead",
                "Herkimer",
                "Hudson",
                "Huntington",
                "Hyde Park",
                "Ilion",
                "Ithaca",
                "Jamestown",
                "Johnstown",
                "Kingston",
                "Lackawanna",
                "Lake Placid",
                "Levittown",
                "Lockport",
                "Mamaroneck",
                "Manhattan",
                "Massena",
                "Middletown",
                "Mineola",
                "Mount Vernon",
                "New Paltz",
                "New Rochelle",
                "New Windsor",
                "New York City",
                "Newburgh",
                "Niagara Falls",
                "North Hempstead",
                "Nyack",
                "Ogdensburg",
                "Olean",
                "Oneida",
                "Oneonta",
                "Ossining",
                "Oswego",
                "Oyster Bay",
                "Palmyra",
                "Peekskill",
                "Plattsburgh",
                "Port Washington",
                "Potsdam",
                "Poughkeepsie",
                "Queens",
                "Rensselaer",
                "Rochester",
                "Rome",
                "Rotterdam",
                "Rye",
                "Sag Harbor",
                "Saranac Lake",
                "Saratoga Springs",
                "Scarsdale",
                "Schenectady",
                "Seneca Falls",
                "Southampton",
                "Staten Island",
                "Stony Brook",
                "Stony Point",
                "Syracuse",
                "Tarrytown",
                "Ticonderoga",
                "Tonawanda",
                "Troy",
                "Utica",
                "Watertown",
                "Watervliet",
                "Watkins Glen",
                "West Seneca",
                "White Plains",
                "Woodstock",
                "Yonkers"
            ],
            "NC": [
                "Asheboro",
                "Asheville",
                "Bath",
                "Beaufort",
                "Boone",
                "Burlington",
                "Chapel Hill",
                "Charlotte",
                "Concord",
                "Durham",
                "Edenton",
                "Elizabeth City",
                "Fayetteville",
                "Gastonia",
                "Goldsboro",
                "Greensboro",
                "Greenville",
                "Halifax",
                "Henderson",
                "Hickory",
                "High Point",
                "Hillsborough",
                "Jacksonville",
                "Kinston",
                "Kitty Hawk",
                "Lumberton",
                "Morehead City",
                "Morganton",
                "Nags Head",
                "New Bern",
                "Pinehurst",
                "Raleigh",
                "Rocky Mount",
                "Salisbury",
                "Shelby",
                "Washington",
                "Wilmington",
                "Wilson",
                "Winston-Salem"
            ],
            "ND": [
                "Bismarck",
                "Devils Lake",
                "Dickinson",
                "Fargo",
                "Grand Forks",
                "Jamestown",
                "Mandan",
                "Minot",
                "Rugby",
                "Valley City",
                "Wahpeton",
                "Williston"
            ],
            "OH": [
                "Akron",
                "Alliance",
                "Ashtabula",
                "Athens",
                "Barberton",
                "Bedford",
                "Bellefontaine",
                "Bowling Green",
                "Canton",
                "Chillicothe",
                "Cincinnati",
                "Cleveland",
                "Cleveland Heights",
                "Columbus",
                "Conneaut",
                "Cuyahoga Falls",
                "Dayton",
                "Defiance",
                "Delaware",
                "East Cleveland",
                "East Liverpool",
                "Elyria",
                "Euclid",
                "Findlay",
                "Gallipolis",
                "Greenville",
                "Hamilton",
                "Kent",
                "Kettering",
                "Lakewood",
                "Lancaster",
                "Lima",
                "Lorain",
                "Mansfield",
                "Marietta",
                "Marion",
                "Martins Ferry",
                "Massillon",
                "Mentor",
                "Middletown",
                "Milan",
                "Mount Vernon",
                "New Philadelphia",
                "Newark",
                "Niles",
                "North College Hill",
                "Norwalk",
                "Oberlin",
                "Painesville",
                "Parma",
                "Piqua",
                "Portsmouth",
                "Put-in-Bay",
                "Salem",
                "Sandusky",
                "Shaker Heights",
                "Springfield",
                "Steubenville",
                "Tiffin",
                "Toledo",
                "Urbana",
                "Warren",
                "Wooster",
                "Worthington",
                "Xenia",
                "Yellow Springs",
                "Youngstown",
                "Zanesville"
            ],
            "OK": [
                "Ada",
                "Altus",
                "Alva",
                "Anadarko",
                "Ardmore",
                "Bartlesville",
                "Bethany",
                "Chickasha",
                "Claremore",
                "Clinton",
                "Cushing",
                "Duncan",
                "Durant",
                "Edmond",
                "El Reno",
                "Elk City",
                "Enid",
                "Eufaula",
                "Frederick",
                "Guthrie",
                "Guymon",
                "Hobart",
                "Holdenville",
                "Hugo",
                "Lawton",
                "McAlester",
                "Miami",
                "Midwest City",
                "Moore",
                "Muskogee",
                "Norman",
                "Oklahoma City",
                "Okmulgee",
                "Pauls Valley",
                "Pawhuska",
                "Perry",
                "Ponca City",
                "Pryor",
                "Sallisaw",
                "Sand Springs",
                "Sapulpa",
                "Seminole",
                "Shawnee",
                "Stillwater",
                "Tahlequah",
                "The Village",
                "Tulsa",
                "Vinita",
                "Wewoka",
                "Woodward"
            ],
            "OR": [
                "Albany",
                "Ashland",
                "Astoria",
                "Baker City",
                "Beaverton",
                "Bend",
                "Brookings",
                "Burns",
                "Coos Bay",
                "Corvallis",
                "Eugene",
                "Grants Pass",
                "Hillsboro",
                "Hood River",
                "Jacksonville",
                "John Day",
                "Klamath Falls",
                "La Grande",
                "Lake Oswego",
                "Lakeview",
                "McMinnville",
                "Medford",
                "Newberg",
                "Newport",
                "Ontario",
                "Oregon City",
                "Pendleton",
                "Port Orford",
                "Portland",
                "Prineville",
                "Redmond",
                "Reedsport",
                "Roseburg",
                "Salem",
                "Seaside",
                "Springfield",
                "The Dalles",
                "Tillamook"
            ],
            "PA": [
                "Abington",
                "Aliquippa",
                "Allentown",
                "Altoona",
                "Ambridge",
                "Bedford",
                "Bethlehem",
                "Bloomsburg",
                "Bradford",
                "Bristol",
                "Carbondale",
                "Carlisle",
                "Chambersburg",
                "Chester",
                "Columbia",
                "Easton",
                "Erie",
                "Franklin",
                "Germantown",
                "Gettysburg",
                "Greensburg",
                "Hanover",
                "Harmony",
                "Harrisburg",
                "Hazleton",
                "Hershey",
                "Homestead",
                "Honesdale",
                "Indiana",
                "Jeannette",
                "Jim Thorpe",
                "Johnstown",
                "Lancaster",
                "Lebanon",
                "Levittown",
                "Lewistown",
                "Lock Haven",
                "Lower Southampton",
                "McKeesport",
                "Meadville",
                "Middletown",
                "Monroeville",
                "Nanticoke",
                "New Castle",
                "New Hope",
                "New Kensington",
                "Norristown",
                "Oil City",
                "Philadelphia",
                "Phoenixville",
                "Pittsburgh",
                "Pottstown",
                "Pottsville",
                "Reading",
                "Scranton",
                "Shamokin",
                "Sharon",
                "State College",
                "Stroudsburg",
                "Sunbury",
                "Swarthmore",
                "Tamaqua",
                "Titusville",
                "Uniontown",
                "Warren",
                "Washington",
                "West Chester",
                "Wilkes-Barre",
                "Williamsport",
                "York"
            ],
            "RI": [
                "Barrington",
                "Bristol",
                "Central Falls",
                "Cranston",
                "East Greenwich",
                "East Providence",
                "Kingston",
                "Middletown",
                "Narragansett",
                "Newport",
                "North Kingstown",
                "Pawtucket",
                "Portsmouth",
                "Providence",
                "South Kingstown",
                "Tiverton",
                "Warren",
                "Warwick",
                "Westerly",
                "Wickford",
                "Woonsocket"
            ],
            "SC": [
                "Abbeville",
                "Aiken",
                "Anderson",
                "Beaufort",
                "Camden",
                "Charleston",
                "Columbia",
                "Darlington",
                "Florence",
                "Gaffney",
                "Georgetown",
                "Greenville",
                "Greenwood",
                "Hartsville",
                "Lancaster",
                "Mount Pleasant",
                "Myrtle Beach",
                "Orangeburg",
                "Rock Hill",
                "Spartanburg",
                "Sumter",
                "Union",
                "Williamsburg",
                "York"
            ],
            "SD": [
                "Aberdeen",
                "Belle Fourche",
                "Brookings",
                "Canton",
                "Custer",
                "De Smet",
                "Deadwood",
                "Hot Springs",
                "Huron",
                "Lead",
                "Madison",
                "Milbank",
                "Mitchell",
                "Mobridge",
                "Pierre",
                "Rapid City",
                "Sioux Falls",
                "Spearfish",
                "Sturgis",
                "Vermillion",
                "Watertown",
                "Yankton"
            ],
            "TN": [
                "Alcoa",
                "Athens",
                "Chattanooga",
                "Clarksville",
                "Cleveland",
                "Columbia",
                "Cookeville",
                "Dayton",
                "Dickson",
                "Dyersburg",
                "East Saint Louis",
                "Elizabethton",
                "Franklin",
                "Gallatin",
                "Gatlinburg",
                "Greeneville",
                "Jackson",
                "Johnson City",
                "Jonesborough",
                "Kingsport",
                "Knoxville",
                "Lebanon",
                "Maryville",
                "Memphis",
                "Morristown",
                "Murfreesboro",
                "Nashville",
                "Norris",
                "Oak Ridge",
                "Shelbyville",
                "Tullahoma"
            ],
            "TX": [
                "Abilene",
                "Alpine",
                "Amarillo",
                "Arlington",
                "Austin",
                "Baytown",
                "Beaumont",
                "Big Spring",
                "Borger",
                "Brownsville",
                "Bryan",
                "Canyon",
                "Cleburne",
                "College Station",
                "Corpus Christi",
                "Crystal City",
                "Dallas",
                "Del Rio",
                "Denison",
                "Denton",
                "Eagle Pass",
                "Edinburg",
                "El Paso",
                "Fort Worth",
                "Freeport",
                "Galveston",
                "Garland",
                "Goliad",
                "Greenville",
                "Harlingen",
                "Houston",
                "Huntsville",
                "Irving",
                "Johnson City",
                "Kilgore",
                "Killeen",
                "Kingsville",
                "Laredo",
                "Longview",
                "Lubbock",
                "Lufkin",
                "Marshall",
                "McAllen",
                "McKinney",
                "Mesquite",
                "Midland",
                "Mission",
                "Nacogdoches",
                "New Braunfels",
                "Odessa",
                "Orange",
                "Pampa",
                "Paris",
                "Pasadena",
                "Pecos",
                "Pharr",
                "Plainview",
                "Plano",
                "Port Arthur",
                "Port Lavaca",
                "Richardson",
                "San Angelo",
                "San Antonio",
                "San Felipe",
                "San Marcos",
                "Sherman",
                "Sweetwater",
                "Temple",
                "Texarkana",
                "Texas City",
                "Tyler",
                "Uvalde",
                "Victoria",
                "Waco",
                "Weatherford",
                "Wichita Falls",
                "Ysleta"
            ],
            "UT": [
                "Alta",
                "American Fork",
                "Bountiful",
                "Brigham City",
                "Cedar City",
                "Clearfield",
                "Delta",
                "Fillmore",
                "Green River",
                "Heber City",
                "Kanab",
                "Layton",
                "Lehi",
                "Logan",
                "Manti",
                "Moab",
                "Monticello",
                "Murray",
                "Nephi",
                "Ogden",
                "Orderville",
                "Orem",
                "Panguitch",
                "Park City",
                "Payson",
                "Price",
                "Provo",
                "Saint George",
                "Salt Lake City",
                "Spanish Fork",
                "Springville",
                "Tooele",
                "Vernal"
            ],
            "VT": [
                "Barre",
                "Bellows Falls",
                "Bennington",
                "Brattleboro",
                "Burlington",
                "Essex",
                "Manchester",
                "Middlebury",
                "Montpelier",
                "Newport",
                "Plymouth",
                "Rutland",
                "Saint Albans",
                "Saint Johnsbury",
                "Sharon",
                "Winooski",
                "Woodstock"
            ],
            "VA": [
                "Abingdon",
                "Alexandria",
                "Bristol",
                "Charlottesville",
                "Chesapeake",
                "Danville",
                "Fairfax",
                "Falls Church",
                "Fredericksburg",
                "Hampton",
                "Hanover",
                "Hopewell",
                "Lexington",
                "Lynchburg",
                "Manassas",
                "Martinsville",
                "New Market",
                "Newport News",
                "Norfolk",
                "Petersburg",
                "Portsmouth",
                "Reston",
                "Richmond",
                "Roanoke",
                "Staunton",
                "Suffolk",
                "Virginia Beach",
                "Waynesboro",
                "Williamsburg",
                "Winchester",
                "Wytheville"
            ],
            "WA": [
                "Aberdeen",
                "Anacortes",
                "Auburn",
                "Bellevue",
                "Bellingham",
                "Bothell",
                "Bremerton",
                "Centralia",
                "Coulee Dam",
                "Coupeville",
                "Ellensburg",
                "Ephrata",
                "Everett",
                "Hoquiam",
                "Kelso",
                "Kennewick",
                "Longview",
                "Moses Lake",
                "Oak Harbor",
                "Olympia",
                "Pasco",
                "Point Roberts",
                "Port Angeles",
                "Pullman",
                "Puyallup",
                "Redmond",
                "Renton",
                "Richland",
                "Seattle",
                "Spokane",
                "Tacoma",
                "Vancouver",
                "Walla Walla",
                "Wenatchee",
                "Yakima"
            ],
            "WV": [
                "Barbour",
                "Beckley",
                "Bluefield",
                "Buckhannon",
                "Charles Town",
                "Charleston",
                "Clarksburg",
                "Elkins",
                "Fairmont",
                "Grafton",
                "Harper's Ferry",
                "Hillsboro",
                "Hinton",
                "Huntington",
                "Keyser",
                "Lewisburg",
                "Logan",
                "Martinsburg",
                "Morgantown",
                "Moundsville",
                "New Martinsville",
                "Parkersburg",
                "Philippi",
                "Point Pleasant",
                "Princeton",
                "Romney",
                "Shepherdstown",
                "South Charleston",
                "Summersville",
                "Weirton",
                "Welch",
                "Wellsburg",
                "Weston",
                "Wheeling",
                "White Sulphur Springs",
                "Williamson"
            ],
            "WI": [
                "Appleton",
                "Ashland",
                "Baraboo",
                "Belmont",
                "Beloit",
                "Eau Claire",
                "Fond du Lac",
                "Green Bay",
                "Hayward",
                "Janesville",
                "Kenosha",
                "La Crosse",
                "Lake Geneva",
                "Madison",
                "Manitowoc",
                "Marinette",
                "Menasha",
                "Milwaukee",
                "Neenah",
                "New Glarus",
                "Oconto",
                "Oshkosh",
                "Peshtigo",
                "Portage",
                "Prairie du Chien",
                "Racine",
                "Rhinelander",
                "Ripon",
                "Sheboygan",
                "Spring Green",
                "Stevens Point",
                "Sturgeon Bay",
                "Superior",
                "Waukesha",
                "Wausau",
                "Wauwatosa",
                "West Allis",
                "West Bend",
                "Wisconsin Dells"
            ],
            "WY": [
                "Buffalo",
                "Casper",
                "Cheyenne",
                "Cody",
                "Douglas",
                "Evanston",
                "Gillette",
                "Green River",
                "Jackson",
                "Lander",
                "Laramie",
                "Newcastle",
                "Powell",
                "Rawlins",
                "Riverton",
                "Rock Springs",
                "Sheridan",
                "Ten Sleep",
                "Thermopolis",
                "Torrington",
                "Worland"
            ], },
            "UK": {

                "EN": [
                  "Bath",
                  "Birmingham",
                  "Bradford",
                  "Brighton & Hove",
                  "Bristol",
                  "Cambridge",
                  "Canterbury",
                  "Carlisle",
                  "Chelmsford",
                  "Chester",
                  "Chichester",
                  "Colchester",
                  "Coventry",
                  "Derby",
                  "Doncaster",
                  "Durham",
                  "Ely",
                  "Exeter",
                  "Gloucester",
                  "Hereford",
                  "Kingston-upon-Hull",
                  "Lancaster",
                  "Leeds",
                  "Leicester",
                  "Lichfield",
                  "Lincoln",
                  "Liverpool",
                  "London",
                  "Manchester",
                  "Milton Keynes",
                  "Newcastle-upon-Tyne",
                  "Norwich",
                  "Nottingham",
                  "Oxford",
                  "Peterborough",
                  "Plymouth",
                  "Portsmouth",
                  "Preston",
                  "Ripon",
                  "Salford",
                  "Salisbury",
                  "Sheffield",
                  "Southampton",
                  "Southend-on-Sea",
                  "St Albans",
                  "Stoke on Trent",
                  "Sunderland",
                  "Truro",
                  "Wakefield",
                  "Wells",
                  "Westminster",
                  "Winchester",
                  "Wolverhampton",
                  "Worcester",
                  "York"
                ],
                "NI": [
                  "Armagh",
                  "Bangor",
                  "Belfast",
                  "Lisburn",
                  "Londonderry",
                  "Newry"
                ],
                "SC": [
                  "Aberdeen",
                  "Dundee",
                  "Dunfermline",
                  "Edinburgh",
                  "Glasgow",
                  "Inverness",
                  "Perth",
                  "Stirling"
                ],
                "WS": [
                  "Bangor",
                  "Cardiff",
                  "Newport",
                  "St Asaph",
                  "St Davids",
                  "Swansea",
                  "Wrexham"
                ],},


            "MM": {
                "ကချင်ပြည်နယ်": [
                    "ကန်ပိုက်တီမြို့",
                    "ကာမိုင်းမြို့",
                    "ချီဖွေမြို့",
                    "ခေါင်လန်ဖူးမြို့",
                    "ဆင်ဘိုမြို့",
                    "ဆဒုံးမြို့",
                    "ဆွမ်ပရာဘွမ်မြို့",
                    "ဆော့လော်မြို့",
                    "တနိုင်းမြို့",
                    "ဒေါ့ဖုန်းယန်မြို့",
                    "နမ္မတီးမြို့",
                    "နောင်မွန်းမြို့",
                    "ပန်နန်းဒင်မြို့",
                    "ပန်ဝါမြို့",
                    "ပူတာအိုမြို့",
                    "ဖားကန့်မြို့",
                    "ဗန်းမော်မြို့",
                    "မံစီမြို့",
                    "မချမ်းဘောမြို့",
                    "မြစ်ကြီးနားမြို့",
                    "မြို့လှမြို့",
                    "မိုးကောင်းမြို့",
                    "မိုးညှင်းမြို့",
                    "မိုးမောက်မြို့",
                    "ရွှေကူမြို့",
                    "ရှင်ဗွေယန်မြို့",
                    "လွယ်ဂျယ်မြို့",
                    "ဝိုင်းမော်မြို့",
                    "ဟိုပင်မြို့",
                    "အင်ဂျန်းယန်မြို့"
                ],
                "ကယားပြည်နယ်": [
                    "လွိုင်ကော်မြို့",
                    "လွိုင်လင်လေးမြို့",
                    "လောပိတမြို့",
                    "ဒီးမော့ဆိုမြို့",
                    "နန်းမယ်ခုံမြို့",
                    "ဖရူဆိုမြို့",
                    "ရှားတောမြို့နယ်",
                    "ရှားတောမြို့",
                    "ဘောလခဲမြို့",
                    "ရွာသစ်မြို့",
                    "ဖားဆောင်းမြို့",
                    "မော်ချီးမြို့",
                    "မယ်စဲ့မြို့"
                ],
                "ချင်းပြည်နယ်": [
                    "ကန်ပက်လက်မြို့",
                    "ကျင်ဒွေးမြို့",
                    "ကျီခါးမြို့",
                    "ခိုင်ကမ်းမြို့",
                    "ဆမီးမြို့",
                    "ဆူရ်ခွားမြို့",
                    "တီးတိန်မြို့",
                    "တွန်းဇံမြို့",
                    "ထန်တလန်မြို့",
                    "နှာဟရိန်မြို့",
                    "ပလက်ဝမြို့",
                    "ဖလမ်းမြို့",
                    "မင်းတပ်မြို့",
                    "မတူပီမြို့",
                    "ရိဒ်ခေါဒါရ်မြို့",
                    "ရေဇွာမြို့",
                    "လိုင်လင်းပီမြို့",
                    "ဝေဘူလမြို့",
                    "ဟားခါးမြို့",
                    "အိုက်ကား",
                    "စာလ်ထောင်(ဟာဆော်)",
                    "ရွာဗါး",
                    "ကျီခါး",
                    "လက်မေ",
                    "ထန်တလန်",
                    "ထုတ်လိုင်",
                    "ကန်ပက်လက်",
                    "လိုထော်",
                    "လုံလဲ",
                    "မတူပီ",
                    "ငဖိုင်းပီ",
                    "ပလက်ဝ",
                    "ပျဉ်ဝ",
                    "ဖို့ဝှိုက်",
                    "ရွာဖန်း",
                    "ဆမီး",
                    "ဆူရ်ခွား",
                    "တေဇန်",
                    "သိုင်းငင်း",
                    "တီးတိန်",
                    "တွန်းဇံ",
                    "ဝေဘူလ",
                    "ဆဘောင်း (ဆဘောင်းတယ်)",
                    "ရိဒ်ခေါဒါရ်",
                    "လုမ်ဘန်",
                    "ဆတ်တား",
                    "ဘွာလ်ခွါး",
                    "တာရွှန်း",
                    "လုမ်ပီး",
                    "လိုင်ဇိုး",
                    "ဖိုင်ဖူ အေ (ဖိုင်ဖား အေ)",
                    "ဖိုင်ဖူ ဘီ (ဖိုင်ဖား ဘီ)",
                    "ရေဇွာ",
                    "ဒင်လာအိုပါး (ဒင်လိုပါး)",
                    "ခပီး",
                    "လုံးရန်",
                    "ဟာအိုဆဲင်",
                    "လုံခင်း",
                    "ဘွာန်လုံး",
                    "လောက်လုံး",
                    "ရမ်ထလို",
                    "ဟရင်ထန်း",
                    "ပါရ်သဲ",
                    "ih",
                    "ရာရီတောင်",
                    "ပါရာ",
                    "ရှာအို",
                    "ခိလှုံ(ဆဘောင်းပီ)",
                    "ပထိန်တလန်",
                    "ရွှေလိုက်ဝ",
                    "ရှင်းလက်ဝ",
                    "မီးဇာ",
                    "မိတ်ဝ",
                    "Kapteel"
                ],
                "ကရင်ပြည်နယ်": [
                    "ဘားအံမြို့",
                    "မြဝတီမြို့",
                    "ကော့ကရိတ်မြို့",
                    "ဖာပွန်မြို့",
                    "သံတောင်ကြီးမြို့",
                    "လှိုင်းဘွဲ့မြို့",
                    "ကြာအင်းဆိပ်ကြီးမြို့",
                    "သံတောင်မြို့",
                    "လိပ်သိုမြို့",
                    "ဘောဂလိမြို့",
                    "ပိုင်ကျုံမြို့",
                    "ရှမ်းရွာသစ်မြို့",
                    "စုကလိမြို့",
                    "ဝေါလေမြိုင်မြို့",
                    "ကျုံဒိုးမြို့",
                    "ဘုရားသုံးဆူမြို့",
                    "ကျိုက်ဒုံမြို့",
                    "ကမမောင်းမြို့"
                  ],
                  "စစ်ကိုင်းတိုင်းဒေသကြီး": [
                    "ကနီမြို့",
                    "ကန့်ဘလူမြို့",
                    "ကလေးမြို့",
                    "ကလေးမြို့ဟောင်း",
                    "ကလေးဝမြို့",
                    "ကသာမြို့",
                    "ကောလင်းမြို့",
                    "ကျောက်မြောင်းမြို့",
                    "ကျွန်းလှမြို့",
                    "ခင်ဦးမြို့",
                    "ခန္တီးမြို့",
                    "ခမ်းပါတ်မြို့",
                    "ချောင်းဦးမြို့",
                    "စစ်ကိုင်းမြို့",
                    "စိုင်ပြင်မြို့",
                    "ဆားတောင်မြို့",
                    "ဆားလင်းကြီးမြို့",
                    "ဆွမ္မရာမြို့",
                    "ဇီးကုန်းမြို့၊ ကန့်ဘလူမြို့နယ်",
                    "တန့်ဆည်မြို့",
                    "တမူးမြို့",
                    "ထန်ပါခွေမြို့",
                    "ထီးချိုင့်မြို့",
                    "ဒီပဲယင်းမြို့",
                    "ဒုံဟီးမြို့",
                    "နန်းယွန်းမြို့",
                    "နဘားမြို့",
                    "ပင်လယ်ဘူးမြို့",
                    "ပန်ဆောင်မြို့",
                    "ပုလဲမြို့",
                    "ဖောင်းပြင်မြို့",
                    "ဗန်းမောက်မြို့",
                    "ဘုတလင်မြို့",
                    "မင်းကင်းမြို့",
                    "မင်းကွန်းမြို့",
                    "မိုပိုင်းလွတ်မြို့",
                    "မုံရွာမြို့",
                    "မော်လိုက်မြို့",
                    "မော်လူးမြို့",
                    "မြင်းမူမြို့",
                    "မြို့သစ်မြို့၊ တမူးခရိုင်",
                    "မြောင်မြို့",
                    "ယင်းမာပင်မြို့",
                    "ရေဦးမြို့",
                    "ရွှေပြည်အေးမြို့",
                    "ရွှေဘိုမြို့",
                    "လဟယ်မြို့",
                    "လေရှီးမြို့",
                    "ဝက်လက်မြို့",
                    "ဝန်းသိုမြို့",
                    "ဟန်လင်းမြို့ဟောင်း",
                    "ဟုမ္မလင်းမြို့",
                    "အင်းတော်မြို့",
                    "အရာတော်မြို့",
                    "အလုံ",
                    "အန့်ပေါ်",
                    "အရာတော်",
                    "ဗန်းမောက်",
                    "ဘော်",
                    "ဘုတ်ကန်",
                    "ဘုတလင်",
                    "ချပ်သင်း",
                    "ချောင်းဦး",
                    "ချင်ပစ်",
                    "ခန္တီး",
                    "လှတော",
                    "ဟုမ္မလင်း",
                    "အင်းတော်",
                    "အင်းရွာ",
                    "ကဒူး",
                    "ကံထူးမ",
                    "ကလေးမြို့",
                    "ကလေးဝ",
                    "ကန့်ဘလူ",
                    "ကနီ",
                    "ကသာ",
                    "ကောင်းဟိန်း",
                    "ကောလင်း",
                    "ကင်း",
                    "ကင်းတပ်",
                    "ခင်ဦး",
                    "ကုက္ကိုကုန်း",
                    "ကူတော်",
                    "ကွမ်းတောင်",
                    "ကျားတတ်",
                    "ကျောက်ကာ",
                    "ကျောက်မြောင်း",
                    "ကွန်းလှ",
                    "လဟယ်",
                    "လောသာ",
                    "လေရှီး",
                    "မလည်",
                    "မံစီ",
                    "မစိန်",
                    "မောင်းထောင်",
                    "မောင်းခမ်း",
                    "မော်လိုက်",
                    "မော်လူး",
                    "မဲဇာ",
                    "မင်းကင်း",
                    "မင်းကွန်း",
                    "မင်းတိုင်ပင်",
                    "ကြောင်ဝင်ဒူး",
                    "ချောင်းဦးရွာ",
                    "မိုးဒါး",
                    "မုဆိုးချုံ",
                    "မုံရွေး",
                    "မြောင်",
                    "မြေမွန်",
                    "မြင်းမူ",
                    "မြင်သာဆိပ်",
                    "မြို့သစ်",
                    "နဘား",
                    "နမ့်တိန်ခွန်(ဂျိတ်ဆော)",
    "နန်းယွန်း",
    "နတ်ချောင်း",
    "ညောင်ကန်",
    "အုန်းတော",
    "အုန်းသာ",
    "ပဒူ",
    "ပုလဲ",
    "ပုလွေရွှေ",
    "ပန်ဆောင်",
    "ပန်းသာ",
    "ဖလံဂုဏ်ရွာ",
    "ဖောင်းပြင်",
    "ပင်လည်ဘူး",
    "ပြောင်ဘုတ်",
    "ရိတုဂါး",
    "ဆားတောင်",
    "ဆားတွင်းကြီး",
    "ဆားလင်းကြီး",
    "စာရေး",
    "ဆွပ်ခွန်",
    "ရှိန်းမကား",
    "ရွှေတွင်း",
    "ဆင်ကုန်း",
    "ဆင်လမောင်း",
    "စစ်တောင်း",
    "ဆွမ္မရာ",
    "ဒီပဲယင်း",
    "ထမံသီ",
    "တတ်လွင်",
    "တန့်ဆည်",
    "တယ်ပင်",
    "သန",
    "သောင်ဝွဋ်",
    "သာစည်",
    "သက္ကယ်ကျင်း",
    "ထီးချိုင့်",
    "တုန်ဟဲ",
    "ဝက်လက်",
    "ဝန်ကြီး",
    "ဝန်းသို",
    "ရေဦး",
    "ယင်းမာပင်",
    "ရွာရှည်",
    "ရွာသစ်ကြီး",
    "စေတီ",
    "ဇီးကုန်း",
    "ခမ်းပါတ်",
    "ထန်းတပင်",
    "သစ်တော်ပေါက်(တ)",
    "သစ်တော်ပေါက်(မ)",
    "သစ္စေးကုန်း(ရ)",
    "သစ္စေးကုန်း(န)",
    "ငှက်ပျောတော",
    "သဲစား",
    "နှမ်းခင်းကြီး",
    "တပိုး",
    "အိုင်လျား",
    "ရွှံအိုင်",
    "ရေသောက်အိုင်",
    "သဲကုန်း",
    "ဒေါင့်ကြီး",
    "ညောင်ကုန်း",
    "ရွာရှည်(တ)",
    "ရွာရှည်(မ)",
    "ခရုတော",
    "နနွင်းတော",
    "နန်းတောင်းရုံ",
    "စိမ်းတန်း",
    "ကပေါင်းကျ",
    "နဘက်ငယ်",
    "နဘက်ကြီး",
    "ဆင်ငယ်",
    "ပေကုန်း",
    "အုတ်ဖိုအိုင်",
    "ပုတီး"],


"တနင်္သာရီတိုင်းဒေသကြီး": [
  "ကရသူရိမြို့",
  "ကလိန်အောင်မြို့",
  "ကော့သောင်းမြို့",
  "ကျွန်းစုမြို့",
  "ခမောက်ကြီးမြို့",
  "တနင်္သာရီမြို့",
  "ထားဝယ်မြို့",
  "ပလမြို့",
  "ပလောက်မြို့",
  "ပုလောမြို့",
  "ပြည်ကြီးမဏ္ဍိုင်မြို့",
  "ဘုတ်ပြင်းမြို့",
  "မေတ္တာမြို့",
  "မောတောင်မြို့",
  "မြိတ်မြို့",
  "ရေဖြူမြို့",
  "လောင်းလုံးမြို့",
  "သရက်ချောင်းမြို့",
  "ပန်းဒလဲကျေးရွာအုပ်စု",
  "မင်းဒပ်",
  "ရငဲ",
  "ကျွဲမင်းကုန်း",
  "ကနက်သိရီ",
  "ကျောက်ခမောက်",
  "ကတွဲ",
  "ဘန်ကချွန်း",
  "လိပ်ဥတောင်",
  "ဘုတ်ပြင်း",
  "ချောင်းဝပြင်",
  "ချူပန်း",
  "ဟာမြင်းကြီး",
  "ဟိန္ဒား",
  "နှမ်းကြဲ",
  "အလယ်စခန်း",
  "လောင်းလုံးမြို့",
  " ကထောင်းနီ",
  "ကလိန်အောင်",
  "ပလောက်မြို့ ",
  "ဆင်ထိုး ",
  "ဆင်ထိုးကြီး",
  "ကံပေါက်",
  "ဇာဒီ",
  "ကရသူရီ",
  "ကျောက်မဲတောင်",
  "ကျောက်တောင်",
  "တောင်သုံးလုံး",
  "ကျွဲကူး",
  "လောင်းလုံး",
  "လေညာ",
  "မလိဝမ်း",
  "ခမောက်ကြီးမြို့",
  "မိန်းမမြို့",
  "မရမ်း",
  "မောင်းမကန်",
  "မိကျောင်းလှောင်",
  "မြိတ်",
  "မေတ္တာ",
  "ပကာရီ",
  "ဇလွန်း",
  "နဘုလယ်",
  "နန်းသွန်",
  "နန်ဒင်",
  "နတ်ကြီးစင်",
  "အုန်းပင်ကွင်း",
  "ပလောက်",
  "ပုလော",
  "ပဲ",
  "ပလ ",
  "စက်တော်ရာ",
  " မီးလောင်ချောင်း",
  "ပင်လယ်ကမ်း",
  "ပြင်ဘုံကြီး",
  " ခန္ဒတီ",
   "ဝါးကုန်း",
  "ပြည်ခြား ",
  "လယ်ဖက် ",
  "ထမင်းမစားရွာ",
  "ဆင်ဖြူတိုင်",
  "စုံစင်ဖျား",
  "ဆင်ကူး",
  " သရက်နှစ်ခွ",
  " ပိတိုင်",
  "သမုတ်",
  "တနင်္သာရီ",
  "တောင်ပျောက်",
  "သဘော့လိပ်",
  "သကျက်တော",
  "သမ်းလှ",
  "သရက်ချောင်း",
  "ကြာအင်းကျေးရွာ",
  "ညောင်ဇင်",
  "ဆင်​ဖြူပြင်",
  "ဝဇွမ်းချောင်း",
  "ရတနာပုံ",
  "ရေဖြူနောက်ဖက်ကမ်း",
  "ဇလွတ်",
  "သာရဘွင်",
  "လဲရှောင်",
  "ထိန်ကြိး",
  "ပရဒတ်",
  "ကတ္တလူကျေးရွာအုပ်စု"
],
"ပဲခူးတိုင်းဒေသကြီး": [
  "ကညွှတ်ကွင်းမြို့",
  "ကဝမြို့",
  "ကေတုမတီမြို့",
  "ကျောက်ကြီးမြို့",
  "ကြို့ပင်ကောက်မြို့",
  "ဆွာမြို့",
  "ဇီးကုန်းမြို့",
  "ဇေယျဝတီမြို့",
  "ညောင်စာရေးမြို့",
  "ညောင်လေးပင်မြို့",
  "တောင်ငူမြို့",
  "ထန်းတပင်မြို့၊ တောင်ငူခရိုင်",
  "ဒိုက်ဦးမြို့",
  "နတ်တလင်းမြို့",
  "ပန်းတောင်းမြို့",
  "ပိန်းဇလုပ်မြို့",
  "ပုတီးကုန်းမြို့",
  "ပေါက်ခေါင်းမြို့",
  "ပေါင်းတည်မြို့",
  "ပေါင်းတလည်မြို့",
  "ပဲခူးမြို့",
  "ပဲနွယ်ကုန်းမြို့",
  "ပြည်မြို့",
  "ပြွန်တန်ဆာမြို့",
  "ဖဒိုမြို့",
  "ဖြူးမြို့",
  "ဘုရားကြီးမြို့",
  "မင်းလှမြို့၊ သာယာဝတီခရိုင်",
  "မဒေါက်မြို့",
  "မိုးညိုမြို့",
  "မြို့လှမြို့၊ တောင်ငူခရိုင်",
  "ရေတာရှည်မြို့",
  "ရေနီမြို့",
  "ရွှေကျင်မြို့",
  "ရွှေတောင်မြို့",
  "လက်ပံတန်းမြို့",
  "ဝေါမြို့",
  "သက္ကလမြို့",
  "သနပ္ပင်မြို့",
  "သာယာဝတီမြို့",
  "သုံးဆယ်မြို့",
  "သဲကုန်းမြို့",
  "အင်းတကော်မြို့",
  "အင်းမမြို့",
  "အုတ်တွင်းမြို့",
  "အုတ်ဖိုမြို့",
  "ဥသျှစ်ပင်မြို့"
],
"မကွေးတိုင်းဒေသကြီး": [
  "ကမ္မမြို့",
  "ကျောက်ထုမြို့",
  "ကျောမြို့",
  "ချောက်မြို့",
  "ငဖဲမြို့",
  "စကုမြို့",
  "စလင်းမြို့",
  "စေတုတ္တရာမြို့",
  "ဆင်ဖြူကျွန်းမြို့",
  "တောင်တွင်းကြီးမြို့",
  "နတ်မောက်မြို့",
  "ပခုက္ကူမြို့",
  "ပွင့်ဖြူမြို့",
  "မကွေးမြို့",
  "မင်းဘူးမြို့",
  "မလွန်မြို့",
  "မြစ်ခြေမြို့",
  "မြိုင်မြို့",
  "မြို့သစ်မြို့",
  "လောင်းရှည်မြို့"
],
"မန္တလေးတိုင်းဒေသကြီး": [
  "ကူမဲမြို့",
  "ကျောက်ဆည်မြို့",
  "ကျောက်ပန်းတောင်းမြို့",
  "ငါန်းဇွန်မြို့",
  "ငါန်းမြာကြီးမြို့",
  "ငါ့သရောက်မြို့",
  "စဉ့်ကိုင်မြို့",
  "စဉ့်ကူးမြို့",
  "စမ္ပာယ်နဂိုရ်",
  "ဆီမီးခုံမြို့",
  "ညောင်ဦးမြို့",
  "တကောင်း",
  "တပ်ကုန်းမြို့",
  "တောင်သာမြို့",
  "တံတားဦးမြို့",
  "နွားထိုးကြီးမြို့",
  "ပင်းယမြို့",
  "ပလိပ်မြို့",
  "ပုဂံ",
  "ပုဂံမြို့သစ်",
  "ပုဂံမြို့ဟောင်း",
  "ပုသိမ်ကြီးမြို့",
  "ပျော်ဘွယ်မြို့",
  "ပြင်ဦးလွင်မြို့",
  "မတ္တရာမြို့",
  "မန္တလေးမြို့",
  "မလှိုင်မြို့",
  "မိတ္ထီလာမြို့",
  "မိုင်းမောမြို့ဟောင်း",
  "မိုးကုတ်မြို့",
  "မြင်စိုင်း",
  "မြင်းခြံမြို့",
  "မြစ်ငယ်မြို့",
  "မြစ်သားမြို့",
  "မတ္တရာမြို့",
  "နေပြည်တော်",
  "ရတနာပုံ နည်းပညာ မြို့သစ်",
  "ရမည်းသင်းမြို့",
  "လှိုင်းတက်မြို့ဟောင်း",
  "ဝတီးမြို့ဟောင်း",
  "ဝမ်းတွင်းမြို့",
  "သပိတ်ကျင်းမြို့",
  "သရက်ခုံ(ရေဇင်း)မြို့ဟောင်း",
  "သာစည်မြို့",
  "အင်းဝမြို့",
  "အမရပူရမြို့"
],
"ရခိုင်ပြည်နယ်": [
  "ကမ်းထောင့်ကြီးမြို့",
  "ကျိန္တလီမြို့",
  "ကျောက်တော်မြို့",
  "ကျောက်ဖြူမြို့",
  "ခမောင်းဆိပ်မြို့",
  "ဂွမြို့",
  "ငပလီမြို့",
  "စစ်တွေမြို့",
  "စနဲမြို့",
  "တပ်တောင်မြို့",
  "တောင်ကုတ်မြို့",
  "တောင်ပြိုလက်ဝဲမြို့",
  "ပုဏ္ဏားကျွန်းမြို့",
  "ပေါက်တောမြို့",
  "ဘူးသီးတောင်မြို့",
  "မင်းပြားမြို့",
  "မအီမြို့",
  "မာန်အောင်မြို့",
  "မောင်တောမြို့",
  "မြင်းလွှတ်မြို့",
  "မြေပုံမြို့",
  "မြောက်ဦးမြို့",
  "ရမ်းဗြဲမြို့",
  "ရသေ့တောင်မြို့",
  "လောင်းကြက်မြို့",
  "လေးတောင်မြို့",
  "ဝေသာလီမြို့",
  "သံတွဲမြို့",
  "အမ်းမြို့"
],
"ရန်ကုန်တိုင်းဒေသကြီး": [
  "ကျောက်တံတား",
  "ကြည့်မြင်တိုင်",
  "စမ်းချောင်း",
  "ဆိပ်ကမ်း",
  "ဒဂုံ",
  "ပန်းဘဲတန်း",
  "ဗဟန်း",
  "လမ်းမတော်",
  "လသာ",
  "အလုံ",
  "တောင်ဥက္ကလာပ",
  "ဒဂုံမြို့သစ်ဆိပ်ကမ်း",
  "ဒဂုံမြို့သစ်တောင်ပိုင်း",
  "ဒဂုံမြို့သစ်မြောက်ပိုင်း",
  "ဒဂုံမြို့သစ်အရှေ့ပိုင်း",
  "ပုဇွန်တောင်",
  "ဗိုလ်တထောင်",
  "မြောက်‌ဥက္ကလာပ",
  "သင်္ဃန်းကျွန်း",
  "ဆိပ်ကြီးခနောင်တို",
  "တာမွေ",
  "ဒလ",
  "ဒေါပုံ",
  "မင်္ဂလာ‌တောင်ညွန့်",
  "ရန်ကင်း",
  "သာကေတ",
  "ကမာရွတ်",
  "မင်္ဂလာဒုံ",
  "မရမ်းကုန်း",
  "ရွှေပြည်သာ",
  "လှိုင်",
  "လှိုင်သာယာ",
  "အင်းစိန်",
  "ကွမ်းခြံကုန်းမြို့",
  "ကိုကိုးကျွန်း",
  "ကော့မှူးမြို့",
  "ကျောက်တန်းမြို့",
  "ခရမ်းမြို့",
  "တံတားမြို့",
  "တွံတေးမြို့",
  "တိုက်ကြီးမြို့",
  "ထန်းတပင်မြို့",
  "ထောက်ကြံ့မြို့",
  "မှော်ဘီမြို့",
  "ရွှေပြည်သာမြို့",
  "လှည်းကူးမြို့",
  "သန်လျင်မြို့",
  "သုံးခွမြို့",
  "အဖျောက်မြို့",
  "ဥက္ကံမြို့"
],
"ရှမ်းပြည်နယ်": [
  "ကလောင်ဖာမြို့",
  "ကလောမြို့",
  "ကာလိမြို့",
  "ကုန်းကြမ်းမြို့",
  "ကျိုင်းတုံမြို့",
  "ကျိုင်းတောင်းမြို့",
  "ကျိုင်းလပ်မြို့",
  "ကျောက်တလုံးကြီးမြို့",
  "ကျောက်မဲမြို့",
  "ကျေးသီးမြို့",
  "ကွတ်ခိုင်မြို့",
  "ကွန်ဟိန်းမြို့",
  "ကွမ်းလုံမြို့",
  "ခိုလမ်မြို့",
  "ချင်းရွှေဟော်မြို့",
  "ခွန်းမားမြို့",
  "ဆီဆိုင်မြို့",
  "ဆောင်ဖမြို့",
  "ညောင်ရွှေမြို့",
  "တန့်ယန်းမြို့",
  "တာချီလိတ်မြို့",
  "တာမိုးညဲမြို့",
  "တာလေမြို့",
  "တုံတာမြို့",
  "တောင်ကြီးမြို့",
  "နန်းပန်မြို့",
  "နမ့်ခမ်းမြို့",
  "နမ့်စန်မြို့",
  "နမ့်ဆန်မြို့",
  "နမ့်ဖိုင်မြို့",
  "နမ္မတူမြို့",
  "နမ်ခမ်းဝူးမြို့",
  "နာဝီးမြို့",
  "နားကောင်မြို့",
  "နားဖန်းမြို့",
  "နောင်ခစ်မြို့",
  "နောင်ချိုမြို့",
  "နောင်တရားမြို့",
  "ပင်းတယမြို့",
  "ပင်လုံမြို့",
  "ပင်လောင်းမြို့",
  "ပန်ခမ့်မြို့",
  "ပန်ဆန်းမြို့",
  "ပန်ဆိုင်းမြို့",
  "ပန်ယန်းမြို့",
  "ပန်လုံမြို့",
  "ပန်ဝိုင်မြို့",
  "ပုံပါကျင်မြို့",
  "ဖယ်ခုံမြို့",
  "ဗထူးတပ်မြို့",
  "မက်မန်းမြို့",
  "မန့်ဟီးရိုးမြို့",
  "မန်ကန်မြို့",
  "မန်တုံမြို့",
  "မန်တွန်းမြို့",
  "မန်မန်ဆိုင်မြို့",
  "မဘိမ်းမြို့",
  "မိုင်းကာမြို့",
  "မိုင်းကိုင်မြို့",
  "မိုင်းခတ်မြို့",
  "မိုင်းခုတ်မြို့",
  "မိုင်းငေါ့မြို့",
  "မိုင်းစံမြို့",
  "မိုင်းဆတ်မြို့",
  "မိုင်းတုံမြို့",
  "မိုင်းနောင်မြို့",
  "မိုင်းပန်မြို့",
  "မိုင်းပေါက်မြို့",
  "မိုင်းပြင်းမြို့",
  "မိုင်းဖျန်မြို့",
  "မိုင်းဖြတ်မြို့",
  "မိုင်းမောမြို့",
  "မိုင်းယုမြို့",
  "မိုင်းယောင်းမြို့",
  "မိုင်းရယ်မြို့",
  "မိုင်းရှူးမြို့",
  "မိုင်းလားမြို့",
  "မိုင်းလုံမြို့",
  "မိုးနဲမြို့",
  "မိုးမိတ်မြို့",
  "မုန်းကိုးမြို့",
  "မုံးထမြို့",
  "မူဆယ်မြို့",
  "မောက်မယ်မြို့",
  "မော်ထိုက်မြို့",
 
  "ယောင်လင်းမြို့",
  "ရင်ဖန့်မြို့",
  "ရပ်စောက်မြို့",
  "ရွာငံမြို့",
  "ရွှေညောင်မြို့",
  "လင်ဟော်မြို့",
  "လင်းခေးမြို့",
  "လားရှိုးမြို့",
  "လုံထန်မြို့",
  "လဲချားမြို့",
  "လွိုင်လင်မြို့",
  "ဝိန်းကောင်မြို့",
  "သိန္နီမြို့",
  "သီပေါမြို့",
  "ဟိုတောင်းမြို့",
  "ဟိုပန်မြို့",
  "ဟိုပုံးမြို့",
  "ဟိုမိန်းမြို့",
  "ဟဲဟိုးမြို့"
],
"ဧရာဝတီတိုင်းဒေသကြီး": [
  "ကနောင်မြို့",
  "ကန်ကြီးထောင့်မြို့",
  "ကျိုက်လတ်မြို့",
  "ကျုံပျော်မြို့",
  "ကျုံမငေးမြို့",
  "ကျောင်းကုန်းမြို့",
  "ကြံခင်းမြို့",
  "ချောင်းသာမြို့",
  "ငပုတောမြို့",
  "ငရုတ်ကောင်းမြို့",
  "ငသိုင်းချောင်းမြို့",
  "ငွေဆောင်မြို့",
  "ဇလွန်မြို့",
  "ညောင်တုန်းမြို့",
  "ထူးကြီးမြို့",
  "ဒေးဒရဲမြို့",
  "ဓနုဖြူမြို့",
  "ပန်းတနော်မြို့",
  "ပုသိမ်မြို့",
  "ပြင်စလူမြို့",
  "ဖျာပုံမြို့",
  "ဘက်ရဲမြို့",
  "ဘိုကလေးမြို့",
  "မအူပင်မြို့",
  "မြန်အောင်မြို့",
  "မြောင်းမြမြို့",
  "ရေကြည်မြို့",
  "ရွှေသောင်ယံမြို့",
  "လပွတ္တာမြို့",
  "လေးမျက်နှာမြို့",
  "ဝါးခယ်မမြို့",
  "သာပေါင်းမြို့",
  "ဟင်္သာတမြို့",
  "အင်္ဂပူမြို့",
  "အိမ်မဲမြို့",
  "အသုတ်မြို့"
],
            
}};

 
    function populateStates() {
        const country = document.getElementById("country").value;
        const stateSelect = document.getElementById("state");
        stateSelect.innerHTML = "<option value=''>Select State</option>";

        if (country === "") return;

        const states = Object.keys(citiesByCountry[country]);
        states.forEach(stateCode => {
            const option = document.createElement("option");
            option.value = stateCode;
            option.text = stateCode;
            stateSelect.appendChild(option);
        });
        populateCities();
    }

    function populateCities() {
        const country = document.getElementById("country").value;
        const state = document.getElementById("state").value;
        const citySelect = document.getElementById("city");
        citySelect.innerHTML = "<option value=''>Select City</option>";

        if (country === "" || state === "") return;

        const cities = citiesByCountry[country][state];
        cities.forEach(city => {
            const option = document.createElement("option");
            option.value = city;
            option.text = city;
            citySelect.appendChild(option);
        });
    }






    document.addEventListener('DOMContentLoaded', function() {
      const cartCount = document.getElementById('cart-count');

      let itemCount = parseInt(sessionStorage.getItem('cartItemCount')) || 0;

      function updateCartCount() {
          cartCount.textContent = itemCount;
          sessionStorage.setItem('cartItemCount', itemCount);
      }

     
      updateCartCount();
  });